import { Poetry, User } from "@prisma/client";
import { getCookie } from "cookies-next";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { db } from "../db";

type PageData = {
  poetries: (Poetry & {
    user: User;
  })[];
  user: Pick<User, "id" | "name">;
};

export const getServerSideProps: GetServerSideProps<PageData> = async ({
  req,
  res,
}) => {
  const cookie = getCookie("userSession", { req, res });

  const user = JSON.parse((cookie || "{}") as string);

  if (!cookie) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  const poetries = await db.poetry.findMany({
    include: { user: true },
  });
  return {
    props: {
      poetries: JSON.parse(JSON.stringify(poetries)) as (Poetry & {
        user: User;
      })[],
      user,
    },
  };
};

const Home: NextPage<PageData> = (props) => {
  const { poetries, user } = props;

  console.log({ user });
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-between w-full">
        <p className="py-8">
          Hi <b>{user.name}</b>, here are some poetries for you:
        </p>
        <Link href="/poetry/new">
          <a className="py-2 px-3 bg-teal-800 text-white shadow-md h-fit inline-flex">
            Create poetry
          </a>
        </Link>
      </div>
      <ul className="flex gap-4 flex-col">
        {poetries.map(
          (poetry) =>
            poetry && (
              <li key={poetry.id} className="border gap-4 flex flex-col p-8">
                <a href={`/poetry/${poetry.id}`}>
                  <span className="text-lg font-bold">{poetry.title}</span>
                </a>
                <span className="text-sm font-medium text-gray-500">
                  {poetry.user.name}
                </span>
                <p>{`${poetry.content.split("\n")[0]}...`}</p>
              </li>
            )
        )}
      </ul>
    </div>
  );
};

export default Home;
